# Generated by Django 2.2.19 on 2023-09-21 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название урока')),
                ('link', models.URLField(max_length=400, verbose_name='Ссылка на урок')),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность урока в секундах')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Урок в продукте',
                'verbose_name_plural': 'Уроки в продукте',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LessonsForUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timming', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время просмотра урока в секундах')),
            ],
            options={
                'verbose_name': 'Урок для пользователя',
                'verbose_name_plural': 'Уроки для пользователя',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание продукта')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации продукта')),
                ('lessons', models.ManyToManyField(related_name='product_lesson', through='products.LessonProduct', to='products.Lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-pub_date'],
            },
        ),
    ]
